version : '3.7'

services:
    app:
        build: ./.docker/php
        networks:
            - backend-net
        working_dir: /var/www
        volumes:
            - .:/var/www:cached
            - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    #Nginx Service
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www:cached
            - ./.docker/nginx/config/:/etc/nginx/conf.d/
            - ./.docker/nginx/certs/:/etc/nginx/certs/
            - ./.docker/nginx/log:/var/log/nginx
        networks:
            - backend-net

    db:
        image: mysql:8
        ports:
            - "3309:3306"
        networks:
            - backend-net
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app

    redis:
      image: 'redis:alpine'
      ports:
        - '6383:6379'
      networks:
        - backend-net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - 8183:80
        environment:
          PMA_HOST: db
          PMA_USER: root
          PMA_PASSWORD: root
        networks:
            - backend-net
networks:
    backend-net:
        driver: bridge
